### ISSUE TITLE
Unable to start language server

### ISSUE THREAD

**Issue by wimjongman** [eclipse/wildwebdeveloper#119]
All languages fail to start the language server with the stacktrace below. Also an occiasional NPE is thrown.

[1] 
eclipse.buildId=4.11.0.I20190115-1800
java.version=1.8.0_151
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/jongw/workspaces/openapi.web/

This is a continuation of log file C:\Users\jongw\workspaces\openapi.web\.metadata\.bak_2.log
Created Time: 2019-01-19 12:47:35.744

org.eclipse.lsp4e
Error
Sun Jan 20 17:32:43 CET 2019
Unable to start language server: HTML Language Server: org.eclipse.wildwebdeveloper.html.HTMLLanguageServer@3d7ff89d

java.io.IOException: Unable to start language server: HTML Language Server: org.eclipse.wildwebdeveloper.html.HTMLLanguageServer@3d7ff89d
	at org.eclipse.lsp4e.server.ProcessStreamConnectionProvider.start(ProcessStreamConnectionProvider.java:44)
	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:206)
	at org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:562)
	at org.eclipse.lsp4e.LanguageServerWrapper.getServerCapabilities(LanguageServerWrapper.java:593)
	at org.eclipse.lsp4e.LanguageServiceAccessor$LSPDocumentInfo.getCapabilites(LanguageServiceAccessor.java:129)
	at org.eclipse.lsp4e.operations.codelens.CodeLensProvider.lambda$0(CodeLensProvider.java:42)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[2]
eclipse.buildId=4.11.0.I20190115-1800
java.version=1.8.0_151
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/jongw/workspaces/openapi.web/

This is a continuation of log file C:\Users\jongw\workspaces\openapi.web\.metadata\.bak_2.log
Created Time: 2019-01-19 12:47:35.744

org.eclipse.jface.text
Error
Sun Jan 20 17:32:43 CET 2019
java.lang.NullPointerException

java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:991)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
	at org.eclipse.lsp4e.operations.codelens.CodeLensProvider.lambda$0(CodeLensProvider.java:45)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at org.eclipse.lsp4e.operations.codelens.CodeLensProvider.lambda$2(CodeLensProvider.java:45)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
	... 8 more

**Comment by wimjongman** [comment]
After installing node and setting it to the path the errors went away.

**Comment by mickaelistria** [comment]
Related: #23 and #55.

**Comment by nobbih** [comment]
How to handle that error when I do not want to install node on my machine ?

**Comment by mickaelistria** [comment]
Try to install from https://download.eclipse.org/wildwebdeveloper/releases/latest/ , and make sure the "node.js embedder" feature gets installed.

**Comment by nobbih** [comment]
Is that installing node.js on my machine ?

**Comment by nobbih** [comment]
I desinstalled the wildwebdeveloper stuff. Now I got rid of the error messages. Only eclipse is complaining about an uncomplete installation. But that I ignore. if node.js is becoming a necessary component I will have to change the development tool.

**Comment by jabby** [comment]
See https://github.com/eclipse/wildwebdeveloper/issues/55#issuecomment-683002305
