### ISSUE TITLE
NPE for projects on network drive

### ISSUE THREAD

**Issue by pebbles186** [eclipse/wildwebdeveloper#162]
Hey,

I'm getting following error "Error while computing completion" -> NullPointerException.
This is the case when I opened a Javascript file in a project which is stored on a network drive.
I'm using eclipse 2019-03 on Windows 10.

When copying the project into my local workspace it works fine.

`!ENTRY org.eclipse.lsp4e 4 0 2019-04-08 14:21:19.330
!MESSAGE java.lang.NullPointerException
!STACK 0
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.computeCompletionProposals(LSContentAssistProcessor.java:96)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup$2.run(AsyncCompletionProposalPopup.java:352)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$8(AsyncCompletionProposalPopup.java:349)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.lambda$4(LSContentAssistProcessor.java:145)
	at org.eclipse.lsp4e.LanguageServiceAccessor.lambda$13(LanguageServiceAccessor.java:517)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	... 4 more`

**Comment by pebbles186** [comment]
I found a workaround. I added the project now via a windows uri:
X:\files\html\development -> code completion works fine
\\FILESTORAGE\files\html\development -> errors occur

**Comment by mickaelistria** [comment]
Indeed, the underlying frameworks rely on a lot on the idea of file and file locations.
It was never tested with network locations AFAIK, but it would be a great addition. The issue is that I'm not aware of many contributors to this project using Windows to take care of it.
Do you have some knowledge in Eclipse plugin development to help troubleshooting that?

**Comment by pebbles186** [comment]
Unfortunately not, I have never done plugin development.
