### ISSUE TITLE
Hovering in js editor leads to errors in the log

### ISSUE THREAD

**Issue by Ludwig-K** [eclipse/wildwebdeveloper#194]
A Bug like this was reported as #10 in 2017.
He appears when hoovering on functions short after opening the js-File with Generic Text editor before the Outline-View is refreshed.
The tooltip will not show as long as the errors are logged, no further limitations.

Eclipse 2019-06
node.js  v10.16.0
WWD-Version 0.4.1.201907091951

Event details:
```
eclipse.buildId=4.12.0.I20190605-1800
java.version=1.8.0_211
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.lsp4e
Error
Tue Jul 16 10:39:57 CEST 2019


java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at org.eclipse.lsp4e.operations.hover.LSBasedHover.getHoverInfo(LSBasedHover.java:108)
	at org.eclipse.ui.internal.genericeditor.hover.CompositeTextHover.getHoverInfo2(CompositeTextHover.java:60)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:169)

```

**Comment by mickaelistria** [comment]
Can you reproduce it with latest releases?

**Comment by Ludwig-K** [comment]
Can't reproduce it, seems to be resolved, Kudos!

**Comment by mickaelistria** [comment]
Thanks for testing!
