### ISSUE TITLE
Lots of exceptions in verify run

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/wildwebdeveloper#200]
The verify of PR #113 is running [now](https://jenkins.eclipse.org/wildwebdeveloper/job/Wildwebdeveloper/job/PR-113/54/console), and there are lots of exceptions in the log. Are these expected?

```
Jul 18, 2019 2:16:51 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint notify
WARNING: Failed to send notification message.
java.lang.NullPointerException
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$1(LanguageServerWrapper.java:216)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.notify(RemoteEndpoint.java:126)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:88)
	at com.sun.proxy.$Proxy29.didClose(Unknown Source)
	at org.eclipse.lsp4e.DocumentContentSynchronizer.lambda$3(DocumentContentSynchronizer.java:157)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.lang.Thread.run(Thread.java:748)

Jul 18, 2019 2:16:51 PM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
SEVERE: An error occurred while processing an incoming message.
java.lang.NullPointerException
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$1(LanguageServerWrapper.java:216)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jonahgraham** [comment]
This bug may indeed belong in LSP4E or LSP4J, but this seemed like the first stop to check.

**Comment by mickaelistria** [comment]
I think it's https://bugs.eclipse.org/bugs/show_bug.cgi?id=546247

**Comment by jonahgraham** [comment]
Thanks @mickaelistria

**Comment by mickaelistria** [comment]
Most of those exception should now have disappeared if you're using a recent snapshot build of LSP4E. Feel free to reopen if it's not the case.
