### ISSUE TITLE
Chrome and Firefox debugger seem to be non-functional with Flatpak

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/wildwebdeveloper#351]
Chrome and Firefox debugger seem to be non-functional with Flatpak

**Comment by mickaelistria** [comment]
@mbooth101 Do you want me to report it to the Eclipse Flatpak github project?

**Comment by rgrunber** [comment]
Seems possibly related to an issue I ran into attempting to debug from Eclipse in flatpak, to a remote session :

!ENTRY org.eclipse.lsp4e.debug 4 5010 2020-11-23 09:48:52.668
!MESSAGE Unexpected exception
!STACK 0
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Cannot find runtime 'node' on PATH. Is 'node' installed?
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at org.eclipse.lsp4e.debug.debugmodel.DSPDebugElement.monitorGet(DSPDebugElement.java:86)
	at org.eclipse.lsp4e.debug.debugmodel.DSPDebugTarget.initialize(DSPDebugTarget.java:183)
	at org.eclipse.lsp4e.debug.launcher.DSPLaunchDelegate.createDebugTarget(DSPLaunchDelegate.java:370)
	at org.eclipse.lsp4e.debug.launcher.DSPLaunchDelegate.launch(DSPLaunchDelegate.java:350)
	at org.eclipse.wildwebdeveloper.debug.node.NodeAttachDebugDelegate.launch(NodeAttachDebugDelegate.java:73)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:807)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:718)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1021)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1224)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Cannot find runtime 'node' on PATH. Is 'node' installed?
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.consume(ReflectiveMessageValidator.java:68)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Also, the launch configuration for "Running node.js application" seems to have some issues regarding saving state. For example, it doesn't save the value of 'port' when applied.

**Comment by mickaelistria** [comment]
@rgrunber: do you have the node embedder feature from Wild Web Developer installed ? That may help.

**Comment by rgrunber** [comment]
> @rgrunber: do you have the node embedder feature from Wild Web Developer installed ? That may help.

I have it installed, but still gave the error message above. I then tried running flatpak as :
`flatpak run --env=PATH=/app/bin:/app/openjdk-11/bin:/usr/bin:$PATH org.eclipse.Sdk`

and that seems to have worked. I now get :

```
java.io.IOException: Cannot run program "/home/rgrunber/workspace-jdt-ls/.metadata/.plugins/org.eclipse.wildwebdeveloper.embedder.node/node-v12.16.1-linux-x64/bin/node": error=26, Text file busy
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1151)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1094)
	at org.eclipse.lsp4e.debug.launcher.DSPLaunchDelegate.launch(DSPLaunchDelegate.java:265)
	at org.eclipse.wildwebdeveloper.debug.node.NodeAttachDebugDelegate.launch(NodeAttachDebugDelegate.java:73)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:807)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:718)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1021)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1224)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: error=26, Text file busy
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessImplFactory.runInSandbox(ProcessImplFactory.java:115)
	at java.base/java.lang.ProcessImplFactory.start(ProcessImplFactory.java:70)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1130)
	... 8 more
```
