### ISSUE TITLE
Errors after update to 0.8.2

### ISSUE THREAD

**Issue by pawelurbanski** [eclipse/wildwebdeveloper#362]
I've installed Eclipse package for JavaScript And Web Developers. Then added Wild Web Developer using the snapshots repository. It installed correctly.
Steps leading to the errors:
1. Created a project and a sample JavaScript file,
2. Started typing: var w = wi (to get completion for teh window object),
3. The completions always started from teh first item in teh alphabetical list or were jumping in a sort of random order,
4. Focus is not set to the parameter name inside the brackets after manually typing a function name.

Here is the log with some additional information about the plugins related to WWD.

!SESSION 2020-02-23 12:09:52.389 -----------------------------------------------
eclipse.buildId=4.14.0.I20191210-0610
java.version=11.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.javascript.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.javascript.product

!ENTRY org.eclipse.egit.ui 2 0 2020-02-23 12:10:01.547
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\Pawel'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.lsp4e 4 0 2020-02-23 12:13:29.951
!MESSAGE java.lang.NoSuchMethodError: org.eclipse.lsp4j.services.TextDocumentService.signatureHelp(Lorg/eclipse/lsp4j/TextDocumentPositionParams;)Ljava/util/concurrent/CompletableFuture;
!STACK 0
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.eclipse.lsp4j.services.TextDocumentService.signatureHelp(Lorg/eclipse/lsp4j/TextDocumentPositionParams;)Ljava/util/concurrent/CompletableFuture;
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.computeContextInformation(LSContentAssistProcessor.java:221)
	at org.eclipse.jface.text.contentassist.ContentAssistant$3.lambda$0(ContentAssistant.java:2049)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.jface.text.contentassist.ContentAssistant$3.run(ContentAssistant.java:2048)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.text.contentassist.ContentAssistant.computeContextInformation(ContentAssistant.java:2045)
	at org.eclipse.jface.text.contentassist.ContentAssistSubjectControlAdapter.computeContextInformation(ContentAssistSubjectControlAdapter.java:379)
	at org.eclipse.jface.text.contentassist.ContextInformationPopup.computeContextInformation(ContextInformationPopup.java:398)
	at org.eclipse.jface.text.contentassist.ContextInformationPopup.lambda$0(ContextInformationPopup.java:188)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.jface.text.contentassist.ContextInformationPopup.showContextProposals(ContextInformationPopup.java:184)
	at org.eclipse.jface.text.contentassist.ContentAssistant$AutoAssistListener.lambda$0(ContentAssistant.java:384)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3963)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3590)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
Caused by: java.lang.NoSuchMethodError: org.eclipse.lsp4j.services.TextDocumentService.signatureHelp(Lorg/eclipse/lsp4j/TextDocumentPositionParams;)Ljava/util/concurrent/CompletableFuture;
	at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.lambda$7(LSContentAssistProcessor.java:216)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.lambda$6(LSContentAssistProcessor.java:220)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

Aditional information about plugins and features:
pluginVendor	EPP JavaScript and Web Package	4.14.0.20191212-1200	org.eclipse.epp.package.javascript.feature
Eclipse Wild Web Developer project	XML support using Language Server	0.6.0.202001131219	org.eclipse.wildwebdeveloper.xml

Version information from properties for feature:
0.8.2.202002201922 (Wild Web Developer)

List of LSP packages installed in the plugins directory:
org.eclipse.lsp4e.debug_0.10.0.201909031808.jar
org.eclipse.lsp4e.debug_0.12.0.202001301838.jar
org.eclipse.lsp4e_0.11.0.201909090701.jar
org.eclipse.lsp4e_0.13.0.201912071343.jar
org.eclipse.lsp4j.debug_0.8.0.v20190822-0801.jar
org.eclipse.lsp4j.debug_0.9.0.v20200130-1210.jar
org.eclipse.lsp4j.jsonrpc.debug_0.8.0.v20190822-0801.jar
org.eclipse.lsp4j.jsonrpc.debug_0.9.0.v20200130-1210.jar
org.eclipse.lsp4j.jsonrpc_0.8.0.v20190822-0801.jar
org.eclipse.lsp4j.jsonrpc_0.9.0.v20200130-1210.jar
org.eclipse.lsp4j_0.8.0.v20190822-0801.jar
org.eclipse.lsp4j_0.9.0.v20200130-1210.jar

**Comment by pawelurbanski** [comment]
I enabled the language server log for JavaScript and here is the output:

[t=1582467935689] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 2230


[t=1582467935696] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","id":"1","method":"initialize","params":{"processId":904,"rootPath":"/C:/Users/Pawel/eclipse-workspace/NVDA/","rootUri":"file:///C:/Users/Pawel/eclipse-workspace/NVDA/","initializationOptions":{"plugins":[{"name":"@angular/language-service","location":"D:\\Apps\\eclipseweb\\eclipse\\plugins\\org.eclipse.wildwebdeveloper_0.5.4.202002201922\\language-servers\\node_modules\\@angular\\language-service"},{"name":"typescript-plugin-css-modules","location":"D:\\Apps\\eclipseweb\\eclipse\\plugins\\org.eclipse.wildwebdeveloper_0.5.4.202002201922\\language-servers\\node_modules\\typescript-plugin-css-modules"},{"name":"typescript-lit-html-plugin","location":"D:\\Apps\\eclipseweb\\eclipse\\plugins\\org.eclipse.wildwebdeveloper_0.5.4.202002201922\\language-servers\\node_modules\\typescript-lit-html-plugin"},{"name":"typescript-eslint-language-service","location":"D:\\Apps\\eclipseweb\\eclipse\\plugins\\org.eclipse.wildwebdeveloper_0.5.4.202002201922\\language-servers\\node_modules\\typescript-eslint-language-service"}]},"capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","delete","rename"],"failureHandling":"undo"},"symbol":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true},"workspaceFolders":true},"textDocument":{"synchronization":{"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"completionItem":{"snippetSupport":true,"documentationFormat":["markdown","plaintext"]}},"hover":{"contentFormat":["markdown","plaintext"]},"signatureHelp":{},"references":{},"documentHighlight":{},"documentSymbol":{"symbolKind":{"valueSet":[18,17,5,14,9,10,22,24,8,1,12,11,20,6,2,3,21,16,19,25,4,7,15,23,26,13]},"hierarchicalDocumentSymbolSupport":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{},"definition":{"linkSupport":true},"typeDefinition":{"linkSupport":true},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dynamicRegistration":true},"codeLens":{},"documentLink":{},"colorProvider":{},"rename":{}}},"clientName":"Eclipse IDE","trace":"off"}}
[t=1582467935897] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","id":"1","result":{"capabilities":{"textDocumentSync":2,"completionProvider":{"triggerCharacters":[".","\"","'","/","@","<"],"resolveProvider":true},"codeActionProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["_typescript.applyWorkspaceEdit","_typescript.applyCodeAction","_typescript.applyRefactoring","_typescript.organizeImports","_typescript.applyRenameFile"]},"hoverProvider":true,"renameProvider":true,"referencesProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",",","<"]},"workspaceSymbolProvider":true,"implementationProvider":true,"typeDefinitionProvider":true,"foldingRangeProvider":true,"callsProvider":true}}}
[t=1582467935921] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 52


[t=1582467935932] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","method":"initialized","params":{}}
[t=1582467936348] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 184


[t=1582467936356] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///C:/Users/Pawel/eclipse-workspace/NVDA/Test/Test.js","languageId":"js","version":1,"text":""}}}
[t=1582467936886] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 160


[t=1582467936895] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","id":"2","method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///C:/Users/Pawel/eclipse-workspace/NVDA/Test/Test.js"}}}
[t=1582467937082] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 199


[t=1582467937099] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","id":"3","method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///C:/Users/Pawel/eclipse-workspace/NVDA/Test/Test.js"},"position":{"line":0,"character":0}}}
[t=1582467937415] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 199


[t=1582467937430] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","id":"4","method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///C:/Users/Pawel/eclipse-workspace/NVDA/Test/Test.js"},"position":{"line":0,"character":0}}}
[t=1582467939837] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","id":"2","result":[]}
[t=1582467939848] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","id":"3","result":[]}
[t=1582467939858] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","id":"4","result":[]}
[t=1582467939898] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///C:/Users/Pawel/eclipse-workspace/NVDA/Test/Test.js","diagnostics":[]}}
[t=1582467940970] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 199


[t=1582467940977] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","id":"5","method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///C:/Users/Pawel/eclipse-workspace/NVDA/Test/Test.js"},"position":{"line":0,"character":0}}}
[t=1582467940985] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","id":"5","result":[]}
[t=1582467941686] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 280


[t=1582467941697] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"version":2,"uri":"file:///C:/Users/Pawel/eclipse-workspace/NVDA/Test/Test.js"},"contentChanges":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"rangeLength":0,"text":"v"}]}}
[t=1582467941984] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///C:/Users/Pawel/eclipse-workspace/NVDA/Test/Test.js","diagnostics":[]}}
[t=1582467942235] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 199


[t=1582467942242] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","id":"6","method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///C:/Users/Pawel/eclipse-workspace/NVDA/Test/Test.js"},"position":{"line":0,"character":1}}}
[t=1582467942252] org.eclipse.wildwebdeveloper.jsts to LSP4E:
{"jsonrpc":"2.0","id":"6","result":[]}
[t=1582467942378] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 280


[t=1582467942389] LSP4E to org.eclipse.wildwebdeveloper.jsts:
{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"version":3,"uri":"file:///C:/Users/Pawel/eclipse-workspace/NVDA/Test/Test.js"},"contentChanges":[{"range":{"start":{"line":0,"character":1},"end":{"line":0,"character":1}},"rangeLength":0,"text":"a"}]}}
[t=1582467942626] LSP4E to org.eclipse.wildwebdeveloper.jsts:
Content-Length: 280

A few things I noticed:
* The version of WWD specified in the release zip downloaded from Github is 0.5.x not 0.8.x,
* After updating the repository for LSP4E to teh latest release, which for some reason was set before to: lsp4e/snapshots does not solve the problem listed in the previous comment,
* I still get the error about no method for symbols.

What would be the way to configure WWD from scratch using the minimum Eclipse package and mantually installing plugins and features?

**Comment by mickaelistria** [comment]
I think LSP4j version (0.9.0) is too recent for this version of LSP4E.
You should try installing LSP4E from snapshot repo.

**Comment by mickaelistria** [comment]
The simultaneous release happened yesterday. Can you please try upgrading with https://wiki.eclipse.org/FAQ_How_do_I_upgrade_Eclipse_IDE%3F#Upgrading_existing_Eclipse_IDE_and_Installed_Features_to_newer_release and report whether this works for you?

**Comment by mickaelistria** [comment]
No news for 3 weeks and no-one mentioned they could reproduce, let's close.
