### ISSUE TITLE
Javascript editor hangs a LOT

### ISSUE THREAD

**Issue by tschallacka** [eclipse/wildwebdeveloper#391]
I have a brand new workstation with i7-9700 @3.60GHz with 32gb ram, and now i've switched over to the wild west editor I have regular hangs when editing javascript files.

I'll be typing, first two characters appear, nothing appears for 5 seconds and then the text I wrote "blindly" appears.

Granted, it's a big project with 11.876 javascript files in total, but until I switched to this editor I never had issues editing individual files.

I tried switching from prototypes to classes but nothing really improved the intermittend laggyness, although I feel like it's worse with prototypes.

It happens when I try to select something, I have to wait like 3 seconds before I can click the cursor to the right spot, then when the cursor blinks I have to carefully select and then wait another few seconds before i can check if I selected enough.

Videos of the behaviour:

https://gofile.io/?c=X2UKpC

Example codes that make it hang:

```javascript
var $ = require('jquery');
var Base = require("@tschallacka/oc.foundation.base");
var APPNAME = 'PackageTypeSwitch';
var global_visible = null;
var Application = function (element, options) 
{
	Base.call(this, APPNAME, element, options);
}; 

Application.prototype = Object.create(Base.prototype); 
Application.prototype.constructor = Application;

Application.prototype.handlers = function(type) {
	this.bind('click', this.$el, this.onClick)	
}
Application.prototype.init = function() {
	if(this.$el.hasClass('active'));
}
Application.prototype.destroy = function() {
	
}

Application.prototype.onClick = function(e) {
	var $clicked = this.$el;
	var packageType = $clicked.data('package-type-switch');
	$('[data-package-type]').hide();
	$('[data-package-type="' + packageType + '"]').show();
	$('[data-package-type-switch]').removeClass('active');
	$('[data-package-type-switch="' + packageType + '"]').addClass('active');
	$(window).trigger('resize');
};

module.exports = Application;
```

and

```googlemaps javascript
var google = window.google;
var $ = require('jquery');

module.exports = class GoogleMapsRender 
{
	
	constructor(args) 
	{
		if(!google) {
			google = window.google;
		}
	    this.routes = {};
	    this.requestedFromGoogle = false;
	    this.options = {
	        mapSaturation:'-100',
	        mapHue:'#000000',
	        jsonbaseRequest:'/csstemplates/template/default/dynamic/google/',
	        markerImage:'/images/needle.png',
	        markerWidth:'17',
	        tripColor:'rgba(255,0,0,0.5)',
	        markerHeight:'38',
	        markerOrientationLeft:'4',
	        zoom:12,
	        markerOrientationBottom:'35',
	        mapCenter : new google.maps.LatLng(42.16953, -75.129335)
	    }
	    for(let val in args) {
	        if(args.hasOwnProperty(val)) {
	            this.options[val] = args[val];
	        }
	    }
	    this.options = args;
	}
	
	init(container) {
		this.map = new google.maps.Map(container, {
            center: this.options.mapCenter,
            mapTypeControlOptions: {
                mapTypeIds: [google.maps.MapTypeId.ROADMAP, 'map_style']
            },
            zoom: this.options.zoom
        });
        let styles = [
            {
                stylers: [
                    { hue: this.options.mapHue },
                    { saturation: this.options.mapSaturation }
                ]
            },{
                featureType: "road",
                elementType: "geometry",
                stylers: [
                    { lightness: 100 },
                    { visibility: "simplified" }
                ]
            },{
                featureType: "administrative.country",
                elementType: "labels",
                stylers: [
                    { visibility: "off" }
                ]
            },{
                featureType: "administrative.province",
                elementType: "labels",
                stylers: [
                    { visibility: "off" }
                ]
            }
        ];
        let styledMap = new google.maps.StyledMapType(styles,
            {name: "Route"});
        this.map.mapTypes.set('map_style', styledMap);
        this.map.setMapTypeId('map_style');

        this.directionsService = new google.maps.DirectionsService;
        this.directionsDisplay = new google.maps.DirectionsRenderer({
            suppressMarkers: true,
            polylineOptions: {
                strokeColor: this.options.tripColor
            }
        });
        this.directionsDisplay.setMap(this.map);
	}
	refreshRoute(routename, data) {
        
        this.loadRouteFromArray(routename,data);

        this.drawRoute(routename);

    }
	loadRoute(routename, callback) {
        var that = this;
        $.getJSON(this.options.jsonbaseRequest+this.options.jsonbaseName+'-'+routename+'-route.json',function(xdata){
            try {
                that.routes[routename].renderData = xdata;
            }
            catch(e) {
                console.log(e.stack);
            }
            callback( that.routes[routename].renderData);
        });
    }
    
	clearAllMarkers()  {
        for(var routename in this.routes) {
            if(this.routes.hasOwnProperty(routename) && typeof routename == 'string') {
                if (this.routes[routename] && typeof this.routes[routename].markers !== 'undefined') {
                    for (i in this.routes[routename].markers) {
                        if (typeof this.routes[routename].markers[i] !== 'undefined') {
                            this.routes[routename].markers[i].setVisible(false);
                        }
                    }
                }
            }
        }
    }
	makeEmptyRoute(routename) {
        this.clearAllMarkers();
        this.routes[routename] = {};
        this.routes[routename].markers = [];
        this.routes[routename].waypoints = [];
        this.routes[routename].legs = [];
        this.routes[routename].renderData = [];
        this.routes[routename].isCompiled = false;
        this.routes[routename].compiled = null;
    }
	addRoutePoint(routename,lon,lat,hasMarker) {
        if(typeof this.routes[routename] === 'undefined') {
            this.makeEmptyRoute(routename);
        }
        this.routes[routename].legs.push({
            location: new google.maps.LatLng(lat, lon),
            lat: lat,
            lon: lon,
            marker: hasMarker=="1"
        });
        this.routes[routename].waypoints.push({
            location: new google.maps.LatLng(lat, lon),
            stopover: true
        });
    }
	loadRouteFromArray(routename,points) {
        if(typeof this.routes[routename] !== 'undefined') {
            this.makeEmptyRoute(routename);
        }
        for(let c in points) {
            this.addRoutePoint(routename,points[c].lon,points[c].lat,points[c].mrk);
        }
    }
	createMarker(latlng) {
        var clickMarkerIcon = {
                url: this.options.markerImage,
                /*The size image file.*/
                size: new google.maps.Size(this.options.markerWidth, this.options.markerHeight),
                /*The point on the image to measure the anchor from. 0, 0 is the top left.*/
                origin: new google.maps.Point(0, 0),
                /*The x y coordinates of the anchor point on the marker. e.g. If your map marker was a drawing pin then the anchor would be the tip of the pin.*/
                anchor: new google.maps.Point(this.options.markerOrientationLeft, this.options.markerOrientationBottom)

            }
        var clickMarker = new google.maps.Marker({
            position: latlng,
            /** to prevent clipping on tile edges */
            optimized: false,
            map: this.map,
            title: '',
            icon: clickMarkerIcon,
            zIndex:20000,
        });
        google.maps.event.addListener(clickMarker, 'mouseout', function() {
        });
        google.maps.event.addListener(clickMarker, 'mouseover', function() {
        });
        return clickMarker
	}
	drawRoute(name) 
	{
        if(this.routes[name].renderData.length === 0) {
            var that = this;
            this.loadRoute(name,function(details) {
                if (details !== null) {
                    that.renderRoute(name);
                }
            });
        }
        else {
            this.renderRoute(name);
        }

    }
	renderRoute(name)
	{
        this.directionsDisplay.setDirections(this.routes[name].renderData[0]);

        var legs = this.routes[name].legs;

        for (let i = 0; i <legs.length; i++) {
            if (Boolean(legs[i].marker)) {
                var marker = this.createMarker(legs[i].location);
                this.routes[name].markers.push(marker);
            }
        }
    }
}

```

**Comment by mickaelistria** [comment]
Does the "error log" view show possibily related issues?
Do you get some features working (like diagnostics, completion....)?

**Comment by tschallacka** [comment]
I have this message a lot in my error log, a lot of them from when I was experimenting for the video
```
class org.eclipse.wst.jsdt.core.dom.EmptyStatement is not assignable to class org.eclipse.wst.jsdt.core.dom.SingleVariableDeclaration

java.lang.ClassCastException: class org.eclipse.wst.jsdt.core.dom.EmptyStatement is not assignable to class org.eclipse.wst.jsdt.core.dom.SingleVariableDeclaration
	at org.eclipse.wst.jsdt.core.dom.ASTNode.checkNewChild(ASTNode.java:1830)
	at org.eclipse.wst.jsdt.core.dom.ASTNode$NodeList.add(ASTNode.java:1216)
	at org.eclipse.wst.jsdt.core.dom.ASTNode$NodeList.add(ASTNode.java:1)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.processFunction(ClosureCompilerASTConverter.java:819)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.process(ClosureCompilerASTConverter.java:229)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.transform(ClosureCompilerASTConverter.java:128)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.transformAndSetProperty(ClosureCompilerASTConverter.java:1680)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.convertToObjectLiteralField(ClosureCompilerASTConverter.java:1151)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.processObjectLiteral(ClosureCompilerASTConverter.java:1071)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.process(ClosureCompilerASTConverter.java:247)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.transform(ClosureCompilerASTConverter.java:128)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.transformAndSetProperty(ClosureCompilerASTConverter.java:1680)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.processBinaryExpression(ClosureCompilerASTConverter.java:510)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.process(ClosureCompilerASTConverter.java:187)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.transform(ClosureCompilerASTConverter.java:128)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.processCommaExpression(ClosureCompilerASTConverter.java:590)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.process(ClosureCompilerASTConverter.java:281)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.transform(ClosureCompilerASTConverter.java:128)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.transformAndSetProperty(ClosureCompilerASTConverter.java:1680)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.processExpressionStatement(ClosureCompilerASTConverter.java:718)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.process(ClosureCompilerASTConverter.java:219)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.transform(ClosureCompilerASTConverter.java:128)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.processAstRoot(ClosureCompilerASTConverter.java:493)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.process(ClosureCompilerASTConverter.java:263)
	at org.eclipse.wst.jsdt.core.dom.ClosureCompilerASTConverter.transform(ClosureCompilerASTConverter.java:128)
	at org.eclipse.wst.jsdt.internal.compiler.closure.ClosureCompiler.parse(ClosureCompiler.java:120)
	at org.eclipse.wst.jsdt.core.dom.ASTParser.createAST(ASTParser.java:652)
	at org.eclipse.wst.jsdt.internal.ui.javaeditor.ASTProvider$1.run(ASTProvider.java:583)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.wst.jsdt.internal.ui.javaeditor.ASTProvider.createAST(ASTProvider.java:576)
	at org.eclipse.wst.jsdt.internal.ui.javaeditor.ASTProvider.getAST(ASTProvider.java:511)
	at org.eclipse.wst.jsdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup.calculateASTandInform(SelectionListenerWithASTManager.java:150)
	at org.eclipse.wst.jsdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup$3.run(SelectionListenerWithASTManager.java:135)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

eclipse.buildId=4.14.0.I20191210-0610
java.version=13.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.php.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.php.product

This is a continuation of log file C:\Users\michael.EXIT-REIZEN\eclipse-workspace\.metadata\.bak_0.log
Created Time: 2020-03-25 11:15:24.981

```

**Comment by mickaelistria** [comment]
It seems like you're not using the editor from Wild Web Developer but the one from JSDT.
Please try "Open With > Generic Editor" for the Wild We Developer" flavour.

**Comment by tschallacka** [comment]
Oh wow... Allright, did not know that. I thought the editor marked with Javascript editor was the one from wild west. Thanks!
