### ISSUE TITLE
Launch NPM cannot handle workspace_loc

### ISSUE THREAD

**Issue by DreierF** [eclipse/wildwebdeveloper#392]
Hi,

I'm trying to create a shareable run configuration of type "Launch NPM". However AFAICS the "package.json" file field seems to only allow an absolute path to the package.json file. I tried the typical `${workspace_loc:/myProject/package.json}` and relative paths, but all of them produce an error when running them:
```
An internal error occurred during: "My Run Config".
Path for project must have only one segment.
```

Using an absolute path is not an option as not all Team members will have the project checked out in the same place obviously.

Is there maybe any workaround to allow me to run a simple `npm start`?

**Comment by mickaelistria** [comment]
I cannot reproduce this issue locally, I tried importing folder https://github.com/eclipse/wildwebdeveloper/tree/master/org.eclipse.wildwebdeveloper.tests/testProjects/eslint as project in workspace, an ran this launch config

![Screenshot from 2020-03-25 16-47-26](https://user-images.githubusercontent.com/469058/77556233-86090f80-6eb8-11ea-8e28-6216b1457925.png)

and it seems to work as the console starts ans shows some imfo
```
npm WARN typescript_eslint_dependencies@1.0.0 No description
npm WARN typescript_eslint_dependencies@1.0.0 No repository field.

audited 276 packages in 0.885s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by mickaelistria** [comment]
A workaround can be to use the "External Program" Launch Configuration, but the NPM Launch is expected to work anyway with variables.
Please provide more details to reproduce.

**Comment by AObuchow** [comment]
@DreierF Are you using Windows, Linux or OSX by the way? Not that its should matter, but it'll help locate the potential issue

**Comment by DreierF** [comment]
I'm using MacOS with Eclipse 2020-03 RCP and RAP Developers + the fix mentioned in https://bugs.eclipse.org/bugs/show_bug.cgi?id=490816#c2 to get a proper PATH

**Comment by mickaelistria** [comment]
Can you try without the mentioned hack? Does a plain dmg of Eclipse IDE manage to use variables in NPM launch?
Also, are variables working for other launch configurations?

**Comment by DreierF** [comment]
After reverting the hack I still get same error. The Eclipse installation is more or less plain. Just did a clean install today. Other launch configs successfully use workspace_loc for the same project.

I additionally found the full stack trace in the error logs:
```
java.lang.IllegalArgumentException: Path for project must have only one segment.
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
	at org.eclipse.core.internal.resources.WorkspaceRoot.getProject(WorkspaceRoot.java:150)
	at org.eclipse.wildwebdeveloper.debug.npm.NpmLaunchDelegate.launch(NpmLaunchDelegate.java:65)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:860)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:719)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1017)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1220)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by mickaelistria** [comment]
Can you please provide exact steps to reproduce the issue from an empty workspace?

**Comment by DreierF** [comment]
Here are the minimal steps to reproduce:
1. Create a new General Project from within Eclipse named com.company.product
2. In the created project run npm init
3. Create a NPM Launch run config with `${workspace_loc:/com.company.product/package.json}` and `test` command
4. Run the run config

I get a `env: node: No such file or directory` without the above mentioned PATH hack and `Path for project must have only one segment.` 

The problem seems to be the project name as it does work for simple project names without `.` in it

**Comment by mickaelistria** [comment]
I've tried those steps and cannot reproduce the issue on Fedora here.
I don't really have a clue what's specifically wrong here and how to investigate it further as I'm a lucky non-owner of a Mac. If you're interested, I'd be glad to explain you how to debug an Eclipse plugin so you can investigate more.

**Comment by JimRichards22** [comment]
I'm getting the same error on Linux. I have nested projects (one for front end and one for backend nested under a parent project). I have a full path to `package.json` and get the same error and the same stacktrace in the error log as @DreierF 

My session data is
```
eclipse.buildId=4.16.0.I20200604-0540
java.version=11.0.7
java.vendor=Ubuntu
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_AU
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product
```
Digging around, the `npm` configuration used to have an option for specifying the project, and this seems to have disappeared.

**Comment by mickaelistria** [comment]
Can you reproduce this isse with latest release?
