### ISSUE TITLE
Problem with creating an HTML file ("Unable to start language server")

### ISSUE THREAD

**Issue by mpolito1969** [eclipse/wildwebdeveloper#415]
Good evening (or good morning, according to your time zone),

I've started using Eclipse a few weeks ago, using EPIC (I'm a Perl programmer trying to build a web application using Eclipse as an IDE).

Everything worked well for some days until today, when I reached the point where I had to create an HTML file.

I created the file in the file system (Linux Ubuntu), went back to Eclipse and made "refresh" on the right directory. The file appeared in the project explorer but when I doubled click on it to open it in the editor I got a lot of errors in the Workspace log saying:

Message:
`Unable to start language server: HTML Language Server: ProcessStreamConnectionProvider [commands=[null, /home/max/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.5.6.202004101621/language-servers/node_modules/vscode-html-languageserver/dist/htmlServerMain.js, --stdio], workingDir=/home/max]`

Exception stack trace:
`java.io.IOException: Unable to start language server: HTML Language Server: ProcessStreamConnectionProvider [commands=[null, /home/max/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.5.6.202004101621/language-servers/node_modules/vscode-html-languageserver/dist/htmlServerMain.js, --stdio], workingDir=/home/max]
	at org.eclipse.lsp4e.server.ProcessStreamConnectionProvider.start(ProcessStreamConnectionProvider.java:50)
	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:213)
	at org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:654)
	at org.eclipse.lsp4e.LanguageServiceAccessor.lambda$14(LanguageServiceAccessor.java:589)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLanguageServers(LanguageServiceAccessor.java:602)
	at org.eclipse.lsp4e.operations.highlight.HighlightReconcilingStrategy.collectHighlights(HighlightReconcilingStrategy.java:202)
	at org.eclipse.lsp4e.operations.highlight.HighlightReconcilingStrategy.lambda$0(HighlightReconcilingStrategy.java:125)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:185)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

Session data:
`eclipse.buildId=4.15.0.I20200305-0155
java.version=1.8.0_252
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.javascript.product
Command-line arguments:  -data file:/home/max/bin/eclipse/javascript-2020-03/eclipse/eclipse-workspace/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.javascript.product`

I made a search on Google but I only find something related to C/C++ and was solved in a way that doesn't apply to me.

Every time I write anything in this HTML files one or more new error lines are appended to the log above.

Does anybody can help me out of this?

(I don't even know if this is the right forum to put this support request into. If not, I'm sorry, would you please point me to the right place?).

Thanks.

Ciao,
Max

**Comment by AObuchow** [comment]
Do you happen to have NodeJS installed? It's required to start up the HTML language server.
I suspect that you don't have it installed as the `ProcessStreamConnectionProvider`'s first argument is `null` when it should probably be the location of the NodeJS executable.

Note that the required version range of NodeJS is 8-13 currently for Wild Web Developer. Support for NodeJS 14 should soon be added.

**Comment by mpolito1969** [comment]
Correct.

I've sometimes seen an error message about a missing node.js but I didn't
realise they were related.

I'll see what is node.js and how to install it.

Thanks.

Ciao,
Max

**Comment by AObuchow** [comment]
@mpolito1969 great! Let us know when you have it installed if your issue is fixed, then we can close this bug :)

@mickaelistria maybe we should make it more clear that Node.js is essential for the core functionality of Wild Web Developer? I forget exactly what the warning message says.

**Comment by mpolito1969** [comment]
Yes, the problem disappeared after I installed node.js.

I had to install it from the tarball distributed on their site because the
Ubuntu package was too old.

Thanks again for your support.

Ciao,
Max

**Comment by AObuchow** [comment]
Glad to hear & my pleasure !
