### ISSUE TITLE
Pending operations left around after executing JS files 

### ISSUE THREAD

**Issue by acarstoiu** [eclipse/wildwebdeveloper#455]
I'm using latest Eclipse 4.16 with latest Wild Web Developer 0.10.0.202006021616. Launching a Node.js application within it **always** leaves behind pending operations in the background.

1. Using the _Run As -> Node program_ context menu to launch the execution of a JS file finishes in the _Console_ view, but leaves a progress bar saying "Launching <path_to_file>.js", hung at 37%, in the _Progress_ view. No errors show up in the workspace log.

1.  Using a launch configuration named "lang" of type _Node.js application_ for the JS file in question exhibits the same problem. But the workspace log contains this:
```
!ENTRY org.eclipse.ui 2 2 2020-06-24 21:19:44.131
!MESSAGE Invalid property category path: org.eclipse.cdt.managedbuilder.ui.properties.Page_head_build (bundle: org.eclipse.cdt.ui, propertyPage: org.eclipse.cdt.managedbuilder.ui.properties.BuildLogPreferencePage)

!ENTRY org.eclipse.core.jobs 4 2 2020-06-24 21:19:44.348
!MESSAGE An internal error occurred during: "Launching lang".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.debug.core.model.DebugElement.fireEvent(DebugElement.java:91)
	at org.eclipse.debug.core.model.DebugElement.fireTerminateEvent(DebugElement.java:138)
	at org.eclipse.lsp4e.debug.debugmodel.DSPDebugTarget.terminated(DSPDebugTarget.java:267)
	at org.eclipse.lsp4e.debug.debugmodel.DSPDebugTarget.initialize(DSPDebugTarget.java:185)
	at org.eclipse.lsp4e.debug.launcher.DSPLaunchDelegate.createDebugTarget(DSPLaunchDelegate.java:370)
	at org.eclipse.lsp4e.debug.launcher.DSPLaunchDelegate.launch(DSPLaunchDelegate.java:350)
	at org.eclipse.wildwebdeveloper.debug.node.NodeRunDAPDebugDelegate.launch(NodeRunDAPDebugDelegate.java:94)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:807)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:718)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1021)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1224)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Occasionally, the execution itself hangs, i.e the _Console_ view is frozen, too. I tried a few cases, but cannot indicate a reproduction scenario for this, as well.

**Comment by mickaelistria** [comment]
I think it's related to this bug/patch targetting LSP4E by @vrubezhny : https://git.eclipse.org/r/c/lsp4e/lsp4e/+/164428 , so hopefully, when this is merged and LSP4E releases the fix, things will work properly,

**Comment by acarstoiu** [comment]
I doubt that.
The patch description speaks about _failed_ launches and that is not the case here - the launches succeed.
