### ISSUE TITLE
"The pipe is being closed"

### ISSUE THREAD

**Issue by davidhedley** [eclipse/wildwebdeveloper#535]
In most cases autocomplete is broken for me with CSS, HTML and JavaScript files. Every time I hit the many "special" keys I get:

![image](https://user-images.githubusercontent.com/6061696/93884338-ad5f5e80-fcda-11ea-9ac0-4ca282b69ed7.png)

I don't see any way of disabling this popup behaviour and it's driving me mad.

Please make a way to disable this. If I want you to suggest a completion then I'll hit Ctrl-Space

**Comment by mickaelistria** [comment]
We won't offer a way to disable completion.
However, we're very interested in fixing this issue so complection works as expected. Can you please describe a bit more about your environment and steps to reproduce this issue?

**Comment by davidhedley** [comment]
You "won't" offer a way to disable it? That sounds like a policy decision and not for a technical reason?
IMHO seems like it's a nobrainer to have the ability to disable something which, when it fails for some users (including me a lot of the time), is incredibly irritating. How about when the completion fails with an exception you just don't produce the popup?

My environment:
Clean install of Eclipse 2020-09 for Java Developers, plus installs of:
	• EPIC
	• Subclipse
	• ECD decomplier
	• Eclipse c/c++ development (CDT)
	• AnyEdit
	• Wild Web developer

After initially running Eclipse, the auto completion seems to work OK. After some unspecified period of time using eclipse, auto completion seems to fail and when it's in the failure state, after loading any HTML or CSS file, any time I hit any of the magic keys, of which there are loads, I get the error popup above.

If there's something you'd like me to do or logs you'd like to see when in the error state then give me a pointer and I'll try to help.

**Comment by mickaelistria** [comment]
> You "won't" offer a way to disable it? That sounds like a policy decision and not for a technical reason?

The technical reason is that fixing bugs is more profitable that investing to implement ways to add them. It's a policy of the project to place the development effort where it has the best impact.

> IMHO seems like it's a nobrainer to have the ability to disable something which, when it fails for some users (including me a lot of the time), is incredibly irritating. How about when the completion fails with an exception you just don't produce the popup?

Because it's a nobrainer doesn't make it a good design choice ;) A good design choice is fixing bugs.

> If there's something you'd like me to do or logs you'd like to see when in the error state then give me a pointer and I'll try to help.

Which OS are you using? Can you please look in <workspace>/.metadata/.log for more information about the failure?

**Comment by davidhedley** [comment]
> Because it's a nobrainer doesn't make it a good design choice ;) A good design choice is fixing bugs.

Indeed, but it's also good practice to program defensively and try to handle exceptions in ways that minimise the end-user impact.

> Which OS are you using? Can you please look in /.metadata/.log for more information about the failure?

Windows 10 build 18362.
Next time it fails I'll have a look in there and post anything that looks relevant.

**Comment by mickaelistria** [comment]
Do you have the node embedder installed? If not, what version of node.js do you have installed locally?

**Comment by davidhedley** [comment]
Node.js is installed on the PC (v12.16.3). I've not explicitly installed anything inside Eclipse to do with node unless it comes as standard with one of the installed packages listed above

**Comment by davidhedley** [comment]
Log entry as follows:

!ENTRY org.eclipse.lsp4e 4 0 2020-09-23 06:49:50.461
!MESSAGE 
!STACK 0
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1950)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2085)
	at org.eclipse.lsp4e.operations.hover.LSPTextHover.getHoverRegion(LSPTextHover.java:225)
	at org.eclipse.ui.internal.genericeditor.hover.CompositeTextHover.getHoverRegion(CompositeTextHover.java:101)
	at org.eclipse.jface.text.TextViewerHoverManager.computeInformation(TextViewerHoverManager.java:128)
	at org.eclipse.jface.text.AbstractInformationControlManager.doShowInformation(AbstractInformationControlManager.java:1101)
	at org.eclipse.jface.text.AbstractHoverInformationControlManager$MouseTracker.mouseHover(AbstractHoverInformationControlManager.java:511)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:212)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4195)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4012)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3612)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:153)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

!ENTRY org.eclipse.lsp4e 4 0 2020-09-23 06:49:50.967
!MESSAGE 
!STACK 0
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1950)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2085)
	at org.eclipse.lsp4e.operations.hover.LSPTextHover.getHoverInfo(LSPTextHover.java:131)
	at org.eclipse.ui.internal.genericeditor.hover.CompositeTextHover.getHoverInfo2(CompositeTextHover.java:60)
	at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)

!ENTRY org.eclipse.lsp4e 4 0 2020-09-23 06:49:52.124
!MESSAGE org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: The pipe is being closed
!STACK 0
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: The pipe is being closed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063)
	at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.computeCompletionProposals(LSContentAssistProcessor.java:105)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$10(AsyncCompletionProposalPopup.java:350)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$9(AsyncCompletionProposalPopup.java:349)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: The pipe is being closed
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$2(LanguageServerWrapper.java:251)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.request(RemoteEndpoint.java:161)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:91)
	at com.sun.proxy.$Proxy29.completion(Unknown Source)
	at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.lambda$1(LSContentAssistProcessor.java:101)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.lambda$0(LSContentAssistProcessor.java:104)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1145)
	at java.base/java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:3160)
	at java.base/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1881)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2062)
	... 11 more
Caused by: java.io.IOException: The pipe is being closed
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:347)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:69)
	... 31 more

**Comment by mickaelistria** [comment]
That's similar to https://github.com/eclipse/corrosion/issues/330

**Comment by mickaelistria** [comment]
I suspect the underlying language server dies unexpectedly for some reason and then the connection is lost.
Can you please try installing the "node.js embedder" from https://download.eclipse.org/wildwebdeveloper/releases/latest/ and report whether it makes things work better for you?

**Comment by davidhedley** [comment]
Assuming you mean this:
![image](https://user-images.githubusercontent.com/6061696/94010901-76528100-fd9e-11ea-942c-8c070a97d15d.png)

I have installed it and I'll see if the issue goes away.

Thanks

**Comment by davidhedley** [comment]
No difference. First thing this morning I get the same error. Initially this:
![image](https://user-images.githubusercontent.com/6061696/94108743-c0d40c00-fe37-11ea-8d20-55a639ecac72.png)
And then back to the same error as before.
I can see the node processes still running. Are you sure there isn't a socket timeout on that pipe? This seems to occur when Eclipse is idle all night and I notice the failure when I remote desktop to it first thing in the morning.
If you get this exception can you just close and relaunch the node processes? Can you just periodically send some data down it to test the connection and/or keep it alive?

**Comment by mickaelistria** [comment]
>  Are you sure there isn't a socket timeout on that pipe?

No, I'm not sure. This "pipe" is a a typical Java process input/output stream connection. It's indeed a good thing to investigate whether some timeouts are in play. Do you have some more hints about how to diagnose it?

**Comment by davidhedley** [comment]
I don't know enough about how it works to make more detailed suggestions so but if you ask me my recommendations would be:

- Enable some kind of keep-alive on the pipe/socket. If not possible with a pipe then consider sending some kind of no-op down it every minute to keep it alive and confirm the other end is also still alive
- If the pipe is broken for whatever reason, restart that component and associated processes

Until then I'll just have to keep restarting Eclipse each time it happens.

**Comment by mickaelistria** [comment]
I've been using Wild Web Developer a lot on the last weeks and didn't get such issue. Did you manage to identify some use-cases that make the issue more probable?
I also found another issue related to node.js startup, which got fixed recently. Please try upgrading to snapshots as it may actually fix this symptom (that's more hope talking than actual reasoning ;)...

**Comment by mickaelistria** [comment]
@davidhedley Did you have the opportunity to try recent snapshot from https://download.eclipse.org/wildwebdeveloper/snapshots ? Do you reproduce this issue with them?

**Comment by davidhedley** [comment]
I've haven't been doing much JS dev over the last few weeks so haven't encountered the issue recently. But having tried it first thing this morning it is working fine. This is still with the 202009081414 build so I'm not sure what has changed for it to now work OK, except I have switched to a new Eclipse workspace. If it happens again I'll try and narrow down the circumstances that cause it. It wasn't too hard before - literally just do nothing in Eclipse for a period of time and it would stop working.

**Comment by mickaelistria** [comment]
Thanks! Let's close then. Please add some comment to reopen if you can see this issue with latest builds.
