### ISSUE TITLE
A ConcurrentModificationException exception on XML Editor start

### ISSUE THREAD

**Issue by vrubezhny** [eclipse/wildwebdeveloper#602]
A `ConcurrentModificationException` exception happens on an XML file opening in editor, when processing the `ResponseMessage` received after `textDocument/documentSymbol` request.

```
!ENTRY org.eclipse.lsp4e 1 0 2021-01-19 19:24:12.613
!MESSAGE RequestMessage
{
  "jsonrpc": "2.0",
  "id": "5",
  "method": "textDocument/documentSymbol",
  "params": {
    "textDocument": {
      "uri": "file:///home/jeremy/projects/runtime-wwd-empty/test/.project"
    }
  }
}
Jan 19, 2021 8:36:28 PM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
SEVERE: An error occurred while processing an incoming message.
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapter.write(CollectionTypeAdapter.java:134)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapter.write(CollectionTypeAdapter.java:40)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.write(MessageTypeAdapter.java:423)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.write(MessageTypeAdapter.java:55)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJson(Gson.java:648)
	at com.google.gson.Gson.toJson(Gson.java:603)
	at com.google.gson.Gson.toJson(Gson.java:583)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.toString(MessageJsonHandler.java:161)
	at org.eclipse.lsp4j.jsonrpc.messages.Message.toString(Message.java:38)
	at org.eclipse.lsp4e.LanguageServerWrapper.logMessage(LanguageServerWrapper.java:394)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$4(LanguageServerWrapper.java:260)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
The problem is that at the moment of serialization of the response message, it's result field is a collection that is still being modified, so the Concurrent Modification exception happens on `message.toString()` in  `https://git.eclipse.org/c/lsp4e/lsp4e.git/tree/org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java#n413`

**Comment by mickaelistria** [comment]
I think it's an issue in LSP4E in general, that can happen when LanguageServerPlugin.DEBUG==true. This is not usually the case with Wild Web Developer. Issue should be reported to LSP4E.
