### ISSUE TITLE
Eclipse opens another IDE sporadically

### ISSUE THREAD

**Issue by nimo23** [eclipse/wildwebdeveloper#605]
After updating to the latest wwd, I take notice of a strange (and not easy tracable) bug.

When using the IDE (for example, going into the pom.xml file or any java file), then on any time (not always) but a few times a new Eclipse-IDE opens in the background saying "workspace is in use", then I close it and after a while it comes again: a new Eclipse IDE opens - I did not opened it by myself! It also opens two IDE's at once in the background. I restarted my machine, closed all programs, nothing helps. I get this error every time:

```
An internal error occurred during: "Setting watch projects on serverHTML Language Server (VSCode)".
java.lang.NullPointerException
```

I also get this error from `org.eclipse.lsp4e`:

```
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1957)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2092)
	at org.eclipse.lsp4e.operations.documentLink.DocumentLinkDetector.detectHyperlinks(DocumentLinkDetector.java:121)
	at org.eclipse.ui.texteditor.HyperlinkDetectorRegistry$HyperlinkDetectorDelegate.detectHyperlinks(HyperlinkDetectorRegistry.java:81)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:289)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:262)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.mouseMove(HyperlinkManager.java:457)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:216)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4443)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4229)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3839)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
```

I don't know if this is related to the bug described above. I already filed a bug here https://bugs.eclipse.org/bugs/show_bug.cgi?id=570607, but maybe it is related to wwd? I cannot find the reason. 

On:
Wild Web Developer v. 0.10.6.202101221720
Eclipse Version: 2020-12 (4.18.0)
Mac OS

**Comment by AObuchow** [comment]
I believe this is a duplicate of https://github.com/eclipse/wildwebdeveloper/issues/601#event-4245092418. The fix for it was recently merged, and you'll need to update WWD using the [snapshot update site](http://download.eclipse.org/wildwebdeveloper/snapshots) to get it.

**Comment by nimo23** [comment]
thanks! yes this was the reason.

**Comment by nimo23** [comment]
Btw, after deinstalling the plugin the overall IDE also feels a lot of faster. I think wwd does a lot of things which decrease the speed of eclipse IDE considerably. I installed the snapshot version which helps against the bug, but the IDE (especially the typing in files) seems somewhat sluggish.
