### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid filter directive

### ISSUE THREAD

**Issue by nimo23** [eclipse/wildwebdeveloper#624]
I updated today to latest snapshot. After restarting eclipse hangs with its splash screen will not start. The log within eclipse.app show this:

!ENTRY org.eclipse.osgi 4 0 2021-02-14 19:24:16.346
!MESSAGE FrameworkEvent ERROR
!STACK 0
java.lang.IllegalArgumentException: Invalid filter directive
	at org.eclipse.osgi.container.ModuleResolutionReport.createOSGiRequirement(ModuleResolutionReport.java:200)
	at org.eclipse.osgi.container.ModuleResolutionReport.printRequirement(ModuleResolutionReport.java:184)
	at org.eclipse.osgi.container.ModuleResolutionReport.printResolutionEntry(ModuleResolutionReport.java:123)
	at org.eclipse.osgi.container.ModuleResolutionReport.getResolutionReport0(ModuleResolutionReport.java:114)
	at org.eclipse.osgi.container.ModuleResolutionReport.printResolutionEntry(ModuleResolutionReport.java:140)
	at org.eclipse.osgi.container.ModuleResolutionReport.getResolutionReport0(ModuleResolutionReport.java:114)
	at org.eclipse.osgi.container.ModuleResolutionReport.printResolutionEntry(ModuleResolutionReport.java:140)
	at org.eclipse.osgi.container.ModuleResolutionReport.getResolutionReport0(ModuleResolutionReport.java:114)
	at org.eclipse.osgi.container.ModuleResolutionReport.getResolutionReportMessage(ModuleResolutionReport.java:211)
	at org.eclipse.osgi.container.Module.start(Module.java:462)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: org.osgi.framework.InvalidSyntaxException: Extraneous trailing characters at ")": (&(osgi.wiring.bundle=org.apache.batik.css)(version=[1.6.0,1.7.0)))
	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse(FilterImpl.java:1341)
	at org.eclipse.osgi.internal.framework.FilterImpl.newInstance(FilterImpl.java:181)
	at org.eclipse.osgi.internal.framework.FilterImpl.newInstance(FilterImpl.java:177)
	at org.eclipse.osgi.container.ModuleResolutionReport.createOSGiRequirement(ModuleResolutionReport.java:198)
	... 18 more

**Comment by nimo23** [comment]
I found the error and solved it:

I searched for the files which eclipse addes today in the plugin-directory:

```
org.eclipse.lsp4e_0.13.5.202102121317.jar
org.apache.xalan_2.7.2.v20201124-1837.jar
org.apache.batik.bridge_1.6.0.v200912221622.jar
org.apache.batik.dom.svg_1.6.0.v200805290154.jar
org.apache.batik.dom_1.6.0.v200912221622.jar
org.apache.batik.parser_1.7.0.v200903091627.jar
org.eclipse.emf.workspace_1.5.1.v20110823-1800.jar
```

I downloaded the batic libs:
https://xmlgraphics.apache.org/batik/download.html

and replaced the following

org.apache.batik.bridge_1.6.0.v200912221622.jar
org.apache.batik.dom.svg_1.6.0.v200805290154.jar
org.apache.batik.dom_1.6.0.v200912221622.jar
org.apache.batik.parser_1.7.0.v200903091627.jar

with the newer versions 1.14. I started eclipse and it works as normal. So maybe you can avoid such issues in future by using the newer libs(1.14) instead of such old libs..

**Comment by mickaelistria** [comment]
Did you identify steps to reproduce this issue?

**Comment by nimo23** [comment]
No, I only updated to current wwd snapshot and after restarting this happend. Currently I have reverted the installation to recover my installation.

**Comment by nimo23** [comment]
No, I only updated to current wwd snapshot and after restarting this happend. I don't know if wwd makes use of batik-libs, if so then try to use latest version instead of old versions. With latest batik-libs, the error does not occur.
