### ISSUE TITLE
Unhandled event loop exception when clickin on an XML CodeLens link

### ISSUE THREAD

**Issue by howlger** [eclipse/wildwebdeveloper#644]
In the [`eclipseide-wild-web-developer-0.11.5-win32.win32.x86_64.zip`](https://download.eclipse.org/wildwebdeveloper/releases/latest/IDEs/eclipseide-wild-web-developer-0.11.5-win32.win32.x86_64.zip) I get an **_Unhandled event loop exception_** when **clicking** on a **_`<n> reference(s)`_** XML CodeLens link.

Steps to reproduce using the following `sample.dtd` file:
```
<!ELEMENT sample (foo, bar)>
<!ELEMENT foo (bar*)>
<!ELEMENT bar (#PCDATA)>
```
1. In _Window > Preferences: XML (Wild Web Developer) > CodeLens_ tick the **_Enable XML CodeLens_** checkbox (see #636)
2. Open `sample.dtd` file (see above)
3. Klick on the `1 reference` (above line 2) or `2 references` (above line 3) XML CodeLens link

Result:
- Expected: Any kind of navigation to the clicked reference(s)
- Actual: No navigation; instead, the following _Unhandled event loop exception_ will be logged:
```
eclipse.buildId=4.18.0.I20201202-1800
java.version=15.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.wildwebdeveloper.product.branding.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.wildwebdeveloper.product.branding.product

org.eclipse.ui
Error
Sun Feb 28 22:18:43 CET 2021
Unhandled event loop exception

java.lang.IllegalArgumentException: The handle object must not have a zero-length identifier
	at org.eclipse.core.commands.common.HandleObjectManager.checkId(HandleObjectManager.java:65)
	at org.eclipse.core.commands.CommandManager.getCommand(CommandManager.java:522)
	at org.eclipse.ui.internal.commands.CommandService.getCommand(CommandService.java:159)
	at org.eclipse.lsp4e.command.CommandExecutor.createEclipseCoreCommand(CommandExecutor.java:212)
	at org.eclipse.lsp4e.command.CommandExecutor.executeCommandClientSide(CommandExecutor.java:185)
	at org.eclipse.lsp4e.command.CommandExecutor.executeCommand(CommandExecutor.java:107)
	at org.eclipse.lsp4e.operations.codelens.LSPCodeMining.performAction(LSPCodeMining.java:79)
	at org.eclipse.jface.text.source.inlined.InlinedAnnotationSupport$MouseTracker.mouseUp(InlinedAnnotationSupport.java:318)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
```

By the way, why it is called _CodeLens_ which is a [trademark owned by Microsoft](https://trademarks.justia.com/865/19/codelens-86519796.html) and not _Code Minings_ in Eclipse (see also [Eclipse bug 526969 comment 15](https://bugs.eclipse.org/bugs/show_bug.cgi?id=526969#c15))?

**Comment by angelozerr** [comment]
As I explained here https://github.com/eclipse/wildwebdeveloper/pull/637#issuecomment-784321470 WWD should implement the XML references command which should execute the same action than `Find references`. 

For CodeLens, it's a LSP definition, @mickaelistria do you think should we update with Code Mining?

**Comment by mickaelistria** [comment]
Are XML Code Lens on by default?
Yes, I think we should use Code Mining in Eclipse IDE as it's the term used in JDT as well.

**Comment by howlger** [comment]
_XML CodeLens_ are disabled by default.

**Comment by angelozerr** [comment]
IMHO, LSP should provide some standardization for command IDs, see https://github.com/microsoft/vscode-languageserver-node/issues/495#issuecomment-787952518

**Comment by mickaelistria** [comment]
> IMHO, LSP should provide some standardization for command IDs

Doing things 1 step at a time is a better approach than expecting a big standardization. For this case, it would be better that LSP standardizes a `client/showLocations` server-to-client operation, which would take as input a bunch of locations and would show it where it fits best (eg in the Search view for Eclipse IDE). The clicking the references code mining would cascade to invocation of a server side command, that server would then turn into a `client/showLocations` message for client to process.
