### ISSUE TITLE
How to disable all language servers programmatically?

### ISSUE THREAD

**Issue by cal101** [eclipse/wildwebdeveloper#666]
I hope this is the correct forum for this.

I am using eclipse JDT in batch mode in a kind of more or less headless mode. (Hi @mickaelistria ;-)
It's currently based on eclipse jee.

When (I think) opening projects I get the following:

```
Mar 22, 2021 12:19:29 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
java.util.concurrent.CompletionException: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1806)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
        at org.eclipse.lsp4e.LanguageServerWrapper.lambda$4(LanguageServerWrapper.java:260)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.lambda$handleRequest$1(RemoteEndpoint.java:281)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
        ... 3 more
Caused by: java.io.IOException: Stream closed
        at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:444)
        at java.base/java.io.OutputStream.write(OutputStream.java:162)
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:69)
        ... 6 more
```

How do I disable all language server support programmatically?

**Comment by mickaelistria** [comment]
For batch/headless stuff, I'd strongly recommend that you build your own package which consists of the minimal things for your operations to run (eg not including Wild Web Developer, LSP4E and so on). With that, you should not have to disable anything, nor face exceptions, and you should feel a noticeable speed up at startup.
HTH

**Comment by cal101** [comment]
Thanks for your answer.
That sounds reasonable and surely helps.
I currently don't know what dependencies are needed but that should be possible to find out.
The project started from the opposite direction: Extending a plugin that was used in the IDE with a command line interface and installing that into a standard eclipse (jee) application.
Having other problems to solve and having that scripted I never questioned this approach.
I had so many problems with maven + tycho that I was happy to not touch that too much.
But having that as a running base line should make it possible to rebuild it as a standalone if that can be done on the command line what I expect.
Should I look into oomph for this because I will need some major parts and take for example eclipse jee or a smaller application as a starting point? (Sizing down way)
Or shall I start with some eclipse app tutorial and size that up to the needs?
The problem is that a true "headless" way as it is typically understood in the eclipse universe is not possible because
there is a lot of stuff I need that that has dependencies into jdt.ui.
Not for real technical reasons but for historical reasons or because it does not make a difference for 99% of the usages.
That's why I consider the "sizing down way": Start with a running environment and strip it down.
If you have suggestions how to continue that would be helpful.

**Comment by mickaelistria** [comment]
> Should I look into oomph for this because I will need some major parts and take for example eclipse jee or a smaller application as a starting point? (Sizing down way)

IMO, Oomph isn't really going to make things simpler for this case which is purely about packaging a tool; while Oomph is about provisioning an IDE which is a more specialized case where plain product packaging doesn't fit that well.
I think all you need is some erefactor.product file with the minimal set of features for it to work and invoke your application. The most tricky part in this file is the configuration of start-level that cannot be easily guessed, so here is a sample: https://git.eclipse.org/c/platform/eclipse.platform.releng.aggregator.git/tree/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.product#n191 or https://git.eclipse.org/c/epp/org.eclipse.epp.packages.git/tree/packages/org.eclipse.epp.package.jee.product/epp.product . Note that EPP doesn't set the start level because it "inherits" them from usage of org.eclipse.platform product; that's probably a pattern you'd like to mimic.
You may be able to export your .product into a dedicated product with PDE or Tycho.

> Or shall I start with some eclipse app tutorial and size that up to the needs?

That should work too.

> That's why I consider the "sizing down way": Start with a running environment and strip it down.

Yes, I think it's a good approach; starting from https://git.eclipse.org/c/epp/org.eclipse.epp.packages.git/tree/packages/org.eclipse.epp.package.jee.product/epp.product and removing everything that doesn't seem necessary.

**Comment by cal101** [comment]
Many many thanks!
epp is exactly what i was looking for yesterday.
I checked oomph which seems to concentrate on installer.
I found cbi which seems to be unused now.
I checked the packages site for a hint how packages are build but did not find anything.

epp i  did not find. :-(
Thanks a lot!

P.S. When I find some spare cycles: Suggestions for an additional project to receive some cleanups?

**Comment by mickaelistria** [comment]
I suspect initial issue is resolved and the lack of activity seem to highlight it's not relevant anymore. Closing.
