### ISSUE TITLE
Cannot register xml catalog when there is a space in path

### ISSUE THREAD

**Issue by apupier** [eclipse/wildwebdeveloper#758]
```
java.net.URISyntaxException: Illegal character in path at index 89: file:/home/apupier/ws/fusetooling-only/.metadata/.plugins/org.eclipse.pde.core/JBossTools Linux x86_64/org.eclipse.osgi/1227/0/.cp/schema/dtd/service-ref_5_0.dtd
	at java.base/java.net.URI$Parser.fail(URI.java:2915)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3086)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3168)
	at java.base/java.net.URI$Parser.parse(URI.java:3116)
	at java.base/java.net.URI.<init>(URI.java:600)
	at java.base/java.net.URL.toURI(URL.java:1018)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.lambda$3(XMLCatalogs.java:75)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.getWTPExtensionCatalog(XMLCatalogs.java:63)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.getAllCatalogs(XMLCatalogs.java:50)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLPreferenceConstants.storePreferencesToLemminxOptions(XMLPreferenceConstants.java:90)
	at org.eclipse.wildwebdeveloper.xml.internal.XMLLanguageServer.mergeCustomInitializationOptions(XMLLanguageServer.java:163)
	at org.eclipse.wildwebdeveloper.xml.internal.XMLLanguageServer.getInitializationOptions(XMLLanguageServer.java:158)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$8(LanguageServerWrapper.java:353)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

```

**Comment by apupier** [comment]
content of mentioned file:

```
<?xml version='1.0' encoding='UTF-8'?>

<!-- 
  $Id: jboss-client_5_0.dtd 58121 2006-11-04 19:57:58Z thomas.diesler@jboss.com $
  
  <!DOCTYPE jboss-web PUBLIC
    "-//JBoss//DTD Web Service Reference 5.0//EN"
    "http://www.jboss.org/j2ee/dtd/service-ref_5_0.dtd">      
-->

<!--
  WebServiceRef customization
-->

<!--
  Runtime settings for a web service reference. In the simplest case,
  there is no runtime information required for a service ref.  Runtime info
  is only needed in the following cases :
  
  * to define the port that should be used to resolve a container-managed port
  * to define default Stub property settings for Stub objects
  * to define the URL of a final WSDL document to be used

  Example:
  
  <service-ref>
   <service-ref-name>OrganizationService</service-ref-name>
   <wsdl-override>file:/wsdlRepository/organization-service.wsdl</wsdl-override>
  </service-ref>

  <service-ref>
   <service-ref-name>OrganizationService</service-ref-name>
   <config-name>Secure Client Config</config-name>
   <config-file>META-INF/jbossws-client-config.xml</config-file>
   <handler-chain>META-INF/jbossws-client-handlers.xml</handler-chain>
  </service-ref>
  
  <service-ref>
   <service-ref-name>SecureService</service-ref-name>
   <service-impl-class>org.jboss.tests.ws.jaxws.webserviceref.SecureEndpointService</service-impl-class>
   <service-qname>{http://org.jboss.ws/wsref}SecureEndpointService</service-qname>
    <port-component-ref>
     <service-endpoint-interface>org.jboss.tests.ws.jaxws.webserviceref.SecureEndpoint</service-endpoint-interface>
     <port-qname>{http://org.jboss.ws/wsref}SecureEndpointPort</port-qname>
     <stub-property>
      <name>javax.xml.ws.security.auth.username</name>
      <value>kermit</value>
     </stub-property>
     <stub-property>
      <name>javax.xml.ws.security.auth.password</name>
      <value>thefrog</value>
     </stub-property>
   </port-component-ref>
  </service-ref>
-->
<!ELEMENT service-ref (service-ref-name, service-impl-class?, service-qname?, config-name?, config-file?, handler-chain?, port-component-ref*, wsdl-override?)>

<!-- 
  The service-ref-name element gives the ENC relative name.
  Overrides @WebServiceRef.name
-->
<!ELEMENT service-ref-name (#PCDATA)>

<!--
  Name of the JAXWS service implementation class.
  Overrides @WebServiceRef.value
-->
<!ELEMENT service-impl-class (#PCDATA)>

<!-- 
  The service-qname element declares the specific WSDL service element.
  Specify the qualified service name in the form defined by QName.valueOf()
  
  Example: 
     <service-qname>{http://somensURI}SomeService</service-qname>
-->
<!ELEMENT service-qname (#PCDATA)>

<!-- 
  The optional handler-chain element is a URL or resource name to a handler chain configuration.
  See: @HandlerChain.file
-->
<!ELEMENT handler-chain (#PCDATA)>

<!-- 
  Information for a port within a service-ref.
  
  Either service-endpoint-interface or wsdl-port or both
  (service-endpoint-interface and wsdl-port) should be specified.  
  
  If both are specified, wsdl-port represents the
  port the container should choose for container-managed port selection.
  
  The same wsdl-port value must not appear in
  more than one port-component-ref entry within the same service-ref.
  
  If a particular service-endpoint-interface is using container-managed port
  selection, it must not appear in more than one port-component-ref entry
  within the same service-ref.
-->
<!ELEMENT port-component-ref (service-endpoint-interface?, port-qname?, config-name?, config-file?, stub-property*)>

<!--
  Fully qualified name of service endpoint interface
-->
<!ELEMENT service-endpoint-interface (#PCDATA)>

<!-- 
  Port used in port-component-ref.  
  Specify the qualified port name in the form defined by QName.valueOf()
  
  Example: 
     <port-qname>{http://somensURI}SomeService</port-qname>
-->
<!ELEMENT port-qname (#PCDATA)>

<!-- 
  The optional config-name element gives the client configuration name that must be present in
  the configuration given by element config-file. Ports that match this port info will be 
  configured with this config name.

  The default is: Standard Client
-->
<!ELEMENT config-name (#PCDATA)>

<!-- 
  The optional config-file element is a URL or resource name for the client configuration.
  Ports that match this port info will be configured with this config file.
  
  The default is: META-INF/standard-jbossws-client-config.xml
-->
<!ELEMENT config-file (#PCDATA)>

<!-- 
  Property values that should be set on a stub before it's returned to 
  to the web service client.  The property names can be any properties supported
  by the StubExt or Stub implementation. 
  
  See javadoc for org.jboss.ws.core.StubExt, javax.xml.rpc.Stub
-->
<!ELEMENT stub-property (prop-name, prop-value)>

<!--
  This text nodes holds a name string.
-->
<!ELEMENT prop-name (#PCDATA)>

<!--
  This text nodes holds a value string.
-->
<!ELEMENT prop-value (#PCDATA)>

<!-- 
  The wsdl-override element the actual wsdl docuement the web service client
  uses to connect to the remote service. 
  
  Overrides @WebServiceRef.wsdlLocation
-->
<!ELEMENT wsdl-override (#PCDATA)>
```

**Comment by apupier** [comment]
the character 89 corresponds to the first space, the real value is `file:/home/apupier/ws/fusetooling-only/.metadata/.plugins/org.eclipse.pde.core/JBossTools Linux x86_64/org.eclipse.osgi/1227/0/.cp/schema/dtd/service-ref_5_0.dtd`

**Comment by apupier** [comment]
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=145096

**Comment by kjsmita6** [comment]
Duplicate issue of #756 (we made a pull request at #757).
