### ISSUE TITLE
wwd slows down automatic eclipse compile step

### ISSUE THREAD

**Issue by nimo23** [eclipse/wildwebdeveloper#775]
I use the latest eclipse IDE and latest (snapshot) version of wwd. I have the problem described in https://bugs.eclipse.org/bugs/show_bug.cgi?id=570794. In short: If I change any java file (does not matter, junit or any other), then I have to wait too long for eclipse compile-step. So I sit on my IDE, click here and there, edit a java file without any sense only to trigger the automatic compile step by eclipse. It can be after 10 seconds or after 2- 5 minutes after ecllipse makes its automatic rebuild. That's too long! I thought that the problem was because of https://bugs.eclipse.org/bugs/show_bug.cgi?id=570794, however, I removed the wwd plugin completely, restarted the IDE and now the rebuild triggers immediately (1-2 seconds) after I change and save a java file. So I assume that wwd prevents this eclipse compile step for any reason. Maybe there is any conflict in rebuilding step from wwd and eclipse which leads to this eclipse defect.

**Comment by mickaelistria** [comment]
That's interesting. Can you please provide exact steps to reproduce this issue, from a fresh Eclipse SDK?

**Comment by nimo23** [comment]
I installed wwd again to look if the issue happens again..what I see at first is, that the following message is shown every few seconds in the error log:

```
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2093)
	at org.eclipse.lsp4e.operations.declaration.OpenDeclarationHyperlinkDetector.detectHyperlinks(OpenDeclarationHyperlinkDetector.java:94)
	at org.eclipse.ui.texteditor.HyperlinkDetectorRegistry$HyperlinkDetectorDelegate.detectHyperlinks(HyperlinkDetectorRegistry.java:81)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:289)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:262)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.mouseMove(HyperlinkManager.java:457)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:216)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4565)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1522)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1545)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1530)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4351)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3927)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$4(LanguageServerWrapper.java:260)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```
![Screenshot at Jan 28 19-32-26](https://user-images.githubusercontent.com/3045549/151602790-9553293c-9fd7-40ec-bf29-8b38fcbfe255.png)



The error message is shown very often in my error log. Maybe this is the cause for the break (or delay) of the eclipse compile step. I deinstalled wwd again. Actually, I don't have time to dig into it as I need t work.

**Comment by mickaelistria** [comment]
What's your OS?

**Comment by nimo23** [comment]
I use Mac OS with current eclipse IDE. Everything works now - the build step is triggered immediately when I edit and save a java file. I deinstalled wwd.

**Comment by mickaelistria** [comment]
Is there any chance you can try to identify what is the root cause of those ResponseErrorException? Are the language servers working well? Do you notice some commands started by Eclipse IDE/Wild Web Developer that fail immediately (as it some arguments were wrong)? What files do you have open that can trigger Wild Web Developer language servers (HTML, CSS, XML, JSON, JS, TS...)?

**Comment by nimo23** [comment]
I have not used wwd for a couple of weeks.. I currently only work on java files and jsf files. Sometimes I open css files with the generic editor. But in my project folder there are a bunch of js/ts/node-modules files -  I don't know what wwd does in the background even if I do not open those files (maybe scanning, revalidation, etc.?).  The error above is an example of this background processes: I did only open java files and a bunch of jsf files, so I do not overuse wwd..

**Comment by mickaelistria** [comment]
In this case, I think it's some WTP-XML validation that initiates creation of XML documents that in turn should start the XML Language Server. So one interesting test would be to close everything, just open an XML file, and see if log shows the same error. If it does (very probable), then it would be interesting to see whether the command that's supposed to start this XML Language server is correct.
