### ISSUE TITLE
NoSuchMethodError with WWD 0.1.0.201810092241

### ISSUE THREAD

**Issue by rkrzewski** [eclipse/wildwebdeveloper#87]
Apparently something is wrong on the classpath.
```
java.lang.NoSuchMethodError: org.eclipse.lsp4j.ServerCapabilities.getCodeActionProvider()Ljava/lang/Boolean;
	at org.eclipse.lsp4e.operations.codeactions.LSPCodeActionMarkerResolution.lambda$0(LSPCodeActionMarkerResolution.java:123)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getInitializedLanguageServer(LanguageServiceAccessor.java:259)
	at org.eclipse.lsp4e.operations.codeactions.LSPCodeActionMarkerResolution.checkMarkerResoultion(LSPCodeActionMarkerResolution.java:121)
	at org.eclipse.lsp4e.operations.codeactions.LSPCodeActionMarkerResolution.hasResolutions(LSPCodeActionMarkerResolution.java:162)
	at org.eclipse.ui.internal.ide.registry.MarkerHelpRegistry.hasResolution(MarkerHelpRegistry.java:181)
```

I'm running Eclipse 4.9.0.I20180906-0745 on JDK 11. If there's something I could do to help diagnosing this, please let me know.

**Comment by jabby** [comment]
Hello, I think we have a little problem on the packaging. Can you give all dependencies installed in your Eclipse IDE?

**Comment by mickaelistria** [comment]
Looks like the lsp4j version range lsp4e's MANIFEST.MF is too lax and
should be restricted more.

>

-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>

**Comment by rkrzewski** [comment]
```
org.eclipse.lsp4e 0.7.1.201809281402
org.eclipse.lsp4j 0.6.0.v20181008-1500
```
Here's the full config dump https://gist.github.com/rkrzewski/483a1f84751830458a1203db513382d2

**Comment by mickaelistria** [comment]
This was a bug in LSP4E that was fixed with http://git.eclipse.org/c/lsp4e/lsp4e.git/commit/?id=05cf51ba1f0614356001a59667717f2bb271bff0
Next build of Wild Web Developer (currently stuck by https://bugs.eclipse.org/bugs/show_bug.cgi?id=541306 ) should receive a newer version of LSP4E with this fix included.

**Comment by mickaelistria** [comment]
A new build was just produced which should have it fixed. Can you please try again? (Make sure the version of LSP4E is more recent by the way).

**Comment by mickaelistria** [comment]
I'm closing it since I'm pretty sure it should be ok now. But feel free to reopen if you still see it with a fresh update.
