### ISSUE TITLE
NullPointer in Wild Web Developer causes POM editor to stop functioning after installing specific plugin

### ISSUE THREAD

**Issue by TomBenjamins** [eclipse/wildwebdeveloper#897]
I have created an issue in the M2E project for this first, but I got the response that I should report a bug here first.
https://github.com/eclipse-m2e/m2e-core/issues/960

https://github.com/eclipse-m2e/m2e-core/issues/960#issuecomment-1264409485

Here are the reproduction steps:

1. Install a clean Eclipse JEE 2022-09 and import a Maven project with a POM in any workspace.
2. See the the new M2e Lemminx based POM editor is working, code completion works, hover works.
3. install the qwickie plugin from the eclipse marketplace (I use this plugin for legacy wicket development)
![image](https://user-images.githubusercontent.com/3390629/193417381-cf0565ee-5873-4d08-8424-7c1c240dfd48.png)
4. restart eclipse
5. Open the pom editor again and hover and code completion is failing with multiple instances of the following error:

eclipse.buildId=4.25.0.I20220831-1800

java.version=18.0.2.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -data file:/D:/eclipse-workspace/ -product org.eclipse.epp.package.jee.product

org.eclipse.lsp4e
Error
Sat Oct 01 17:48:31 CEST 2022
java.lang.NullPointerException: Cannot invoke "java.net.URL.getProtocol()" because "url" is null

java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "java.net.URL.getProtocol()" because "url" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.getProtocol()" because "url" is null
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.createURI(XMLCatalogs.java:132)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.lambda$3(XMLCatalogs.java:87)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.getWTPExtensionCatalog(XMLCatalogs.java:65)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.getAllCatalogs(XMLCatalogs.java:52)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLPreferenceConstants.storePreferencesToLemminxOptions(XMLPreferenceConstants.java:90)
	at org.eclipse.wildwebdeveloper.xml.internal.XMLLanguageServer.mergeCustomInitializationOptions(XMLLanguageServer.java:168)
	at org.eclipse.wildwebdeveloper.xml.internal.XMLLanguageServer.getInitializationOptions(XMLLanguageServer.java:163)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$0(LanguageServerWrapper.java:241)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more

![image](https://user-images.githubusercontent.com/3390629/193417608-f13af1f5-5222-4135-8da4-a1dbe42022b2.png)

6. uninstall qwickie plugin from eclipse marketplace and restart system
7. everything works as expected. 

According to https://github.com/mickaelistria the following should be fixed:
Wild Web Developer reads a nonexistent/malfolmed URL and fails hard with a Nullpointer. 

It should be changed to be logged and not breaking.

If you require additional information, please let me know.

greetings,
Tom

**Comment by mickaelistria** [comment]
Thanks. Would you be interested in trying to submit a PR for that?

**Comment by TomBenjamins** [comment]
Do you mean for the issue described here?

**Comment by TomBenjamins** [comment]
Or for the qwickie issue?

**Comment by mickaelistria** [comment]
The one here; the stack does point to the place where change could be made and I don't expect it to be difficult.

**Comment by TomBenjamins** [comment]
I have never made a pull request in github before, shoud I fork it and then commit the fix and then create the pull request?

**Comment by mickaelistria** [comment]
> I have never made a pull request in github before

There's a first time to everything ;)

>  shoud I fork it and then commit the fix and then create the pull request?

Exactly, you explain it like you already did it a thousand times!

**Comment by TomBenjamins** [comment]
I will give it a shot, and let's see what happens.... 8-)

**Comment by TomBenjamins** [comment]
@mickaelistria I think I just finished it, it was a very simple fix indeed.
What is supposed to happen now?

greetings Tom
