### ISSUE TITLE
Error starting Running Chrome Debug Instance

### ISSUE THREAD

**Issue by wesleybl** [eclipse/wildwebdeveloper#917]
When I start `Running Chrome Debug Instance`, I get the error:

```shell

!ENTRY org.eclipse.core.jobs 4 2 2022-10-26 14:56:32.883
!MESSAGE An internal error occurred during: "Launching New_configuration".
!STACK 0
java.lang.NoClassDefFoundError: Could not initialize class com.google.gson.internal.reflect.ReflectionAccessor
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.<init>(ReflectiveTypeAdapterFactory.java:53)
	at com.google.gson.Gson.<init>(Gson.java:286)
	at com.google.gson.GsonBuilder.create(GsonBuilder.java:626)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.<init>(MessageJsonHandler.java:61)
	at org.eclipse.lsp4j.jsonrpc.debug.json.DebugMessageJsonHandler.<init>(DebugMessageJsonHandler.java:26)
	at org.eclipse.lsp4j.jsonrpc.debug.DebugLauncher$Builder.createJsonHandler(DebugLauncher.java:207)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.create(Launcher.java:319)
	at org.eclipse.lsp4j.jsonrpc.debug.DebugLauncher.createIoLauncher(DebugLauncher.java:153)
	at org.eclipse.lsp4j.jsonrpc.debug.DebugLauncher.createLauncher(DebugLauncher.java:121)
	at org.eclipse.lsp4j.debug.launch.DSPLauncher.createClientLauncher(DSPLauncher.java:115)
	at org.eclipse.lsp4e.debug.debugmodel.DSPDebugTarget.createLauncher(DSPDebugTarget.java:206)
	at org.eclipse.lsp4e.debug.debugmodel.DSPDebugTarget.initialize(DSPDebugTarget.java:178)
	at org.eclipse.lsp4e.debug.launcher.DSPLaunchDelegate.createDebugTarget(DSPLaunchDelegate.java:370)
	at org.eclipse.lsp4e.debug.launcher.DSPLaunchDelegate.launch(DSPLaunchDelegate.java:350)
	at org.eclipse.wildwebdeveloper.debug.AbstractHTMLDebugDelegate.launchWithParameters(AbstractHTMLDebugDelegate.java:44)
	at org.eclipse.wildwebdeveloper.debug.chrome.ChromeAttachDebugDelegate.launch(ChromeAttachDebugDelegate.java:43)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:806)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:717)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1021)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1224)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: com/google/gson/internal/JavaVersion [in thread "Worker-16: Launching New_configuration"]
	at com.google.gson.internal.reflect.ReflectionAccessor.<clinit>(ReflectionAccessor.java:36)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.<init>(ReflectiveTypeAdapterFactory.java:53)
	at com.google.gson.Gson.<init>(Gson.java:286)
	at com.google.gson.GsonBuilder.create(GsonBuilder.java:626)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.<init>(MessageJsonHandler.java:61)
	at org.eclipse.lsp4j.jsonrpc.debug.json.DebugMessageJsonHandler.<init>(DebugMessageJsonHandler.java:26)
	at org.eclipse.lsp4j.jsonrpc.debug.DebugLauncher$Builder.createJsonHandler(DebugLauncher.java:207)
	at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.create(Launcher.java:319)
	at org.eclipse.lsp4j.jsonrpc.debug.DebugLauncher.createIoLauncher(DebugLauncher.java:153)
	at org.eclipse.lsp4j.jsonrpc.debug.DebugLauncher.createLauncher(DebugLauncher.java:121)
	at org.eclipse.lsp4j.debug.launch.DSPLauncher.createClientLauncher(DSPLauncher.java:115)
	at org.eclipse.lsp4e.debug.debugmodel.DSPDebugTarget.createLauncher(DSPDebugTarget.java:206)
	at org.eclipse.lsp4e.debug.debugmodel.DSPDebugTarget.initialize(DSPDebugTarget.java:178)
	at org.eclipse.lsp4e.debug.launcher.DSPLaunchDelegate.createDebugTarget(DSPLaunchDelegate.java:370)
	at org.eclipse.lsp4e.debug.launcher.DSPLaunchDelegate.launch(DSPLaunchDelegate.java:350)
	at org.eclipse.wildwebdeveloper.debug.node.NodeAttachDebugDelegate.launch(NodeAttachDebugDelegate.java:74)
	... 5 more
```

I'm using Eclipse 4.25.0 with Java 18

**Comment by akurtakov** [comment]
Eclipse 4.25 requires Java 11 at least. So would you please check your configuration.

**Comment by wesleybl** [comment]
Oh sorry. Even though my system's java is 8, it looks like Eclipse is using its own java. And my `eclipse.ini` looks like this:

```ini
-startup
plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.600.v20220720-1916
-product
org.eclipse.epp.package.java.product
-showsplash
org.eclipse.epp.package.common
--launcher.defaultAction
openFile
--launcher.defaultAction
openFile
--launcher.appendVmargs
-vm
plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_18.0.1.v20220515-1614/jre/bin
-vmargs
-Dosgi.requiredJavaVersion=17
-Dosgi.instance.area.default=@user.home/eclipse-workspace
-Dsun.java.command=Eclipse
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=11
-Dosgi.dataAreaRequiresExplicitInit=true
-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true
-Xms256m
-Xmx2048m
--add-modules=ALL-SYSTEM
```

So it looks like it's using Java 18. I've updated the description.

**Comment by akurtakov** [comment]
I just tried it locally on my Fedora 37 using Chrome 107 and didn't face the issue. Please share things like operating system, nodejs version, chrome version , wildweb version and exact steps to reproduce the issue.

**Comment by wesleybl** [comment]
I'm using:

```
Ubuntu 22
node 16.17.0
Chrome 105
wildweb 0.15.0
```

Steps to reproduce:

- I created a react application:

```shell
npx create-react-app my-app
cd my-app
npm start
```

- I created an eclipse project in my-app folder.
- I closed all Chrome windows.
- Access the Eclipse menu:

Run -> Debug Configurations -> Running Chrome Debug Instance

And create a new configuration.

- I filled the URL field with: http://localhost:3000
- I clicked Apply
- I clicked Debug

@akurtakov Did you do anything other than that?

**Comment by akurtakov** [comment]
I followed your steps exactly and Chrome launched just fine.

**Comment by wesleybl** [comment]
@akurtakov I updated to wildweb 0.15.1 and the problem no longer occurs. Thank you for your help!

If you have a chrome window open, when I click on Debug, the application does not appear, and a blank tab is loaded, at the url "about:blank". But that's another problem.

Thanks!
