### ISSUE TITLE
MacOS Ventura 13 - Eclipse crashes when using the 'Generic Text Editor' for JS files

### ISSUE THREAD

**Issue by florianstephan01** [eclipse/wildwebdeveloper#940]
Since the upgrade to MacOS Ventura 13, i am no longer able to use the 'Generic Text Editor' for JS files. When the cursor hits a variable or a statement, the whole IDE crashes. I attached the dump.

----
Eclipse 2022-09
OpenJDK Runtime Environment SapMachine (build 19.0.1+10-sapmachine)
[eclipse_crash_report.txt](https://github.com/eclipse/wildwebdeveloper/files/9930651/eclipse_crash_report.txt)

**Comment by bmatasar** [comment]
I can confirm crash at almost any edit action of a javascript file.
Started eclipse with `-debug -consoleLog` crashes with the following stack trace:

`Uncaught exception received.
Error: Connection is closed.
    at se (~/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:33782)
    at Object.sendNotification (~/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:34678)
    at m.send (~/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:133296)
    at m.error (~/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:133096)
    at ~/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:35381
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Uncaught exception received.
Error: Connection is closed.
    at se (~/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:33782)
    at Object.sendNotification (~/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:34678)
    at Object.sendNotification (~/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:140489)
    at process.exit (~/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:174318)
    at Socket.<anonymous> (~/.p2/pool/plugins/org.eclipse.wildwebdeveloper_0.6.0.202206151321/node_modules/eslint-server/out/eslintServer.js:1:155291)
    at Socket.emit (node:events:538:35)
    at Pipe.<anonymous> (node:net:687:12)`

**Comment by akurtakov** [comment]
This is caused by browser issue or incompatibility with this Mac version. There is nothing to be done at WildWebDeveloper side. See https://github.com/eclipse-platform/eclipse.platform.swt/issues/452 for the SWT bug.

**Comment by kjsmita6** [comment]
I'm having this crash with XML editors too, specifically the Maven POM editor which uses WWD. Doesn't always happen, just sometimes if I'm tying the application will crash but other times it's ok. I guess we hope there is a fix upstream.

**Comment by wnm3** [comment]
I'm having this problem on the latest version of Eclipse and latest MacOS. After searching and changing a file. Clicking elsewhere in that JavaScript files causes Eclipse to blow up.

Please reopen...

**Comment by kjsmita6** [comment]
@wnm3 this was closed as there is nothing to be done here. This is a bug in macos. Most of the conversation is happening here https://github.com/eclipse-platform/eclipse.platform.swt/issues/452.

**Comment by wnm3** [comment]
The bug I've encountered has nothing to do with browsing, just using the editor opened when clicking on a line in a JavaScript file in search results, making a change, then clicking elsewhere in the file. It is all related to the editor.

I suspect one possible problem is, the search results open the first found result which happens to be an obfuscated .js file from the build of carbon/react that is a single very long line, which may use a lot of memory as the "line" is attempted to be displayed in the console.

**Comment by wnm3** [comment]
I believe this is the generic Text Editor (based on looking at its preferences).

**Comment by wnm3** [comment]
I opened an issue in the wildwebdeveloper as that is what my exception shows very similar to what is described above. https://github.com/eclipse/wildwebdeveloper/issues/1060
